service: serverlessapi

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverlessapiuploadbucket
