service: serverlessapi

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-s3-sync

functions:
  hello:
    handler: handler.hello

custom:
  s3Sync:
    - bucketName: serverlessapiuploadbucket
      localDir: upload

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverlessapiuploadbucket
