service: serverlessapi

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverlessapiuploadbucket
